USE [master]
GO
/****** Object:  Database [QuikShopDB]    Script Date: 12/15/2024 11:33:35 PM ******/
CREATE DATABASE [QuikShopDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuikShopDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QuikShopDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuikShopDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QuikShopDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QuikShopDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuikShopDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QuikShopDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuikShopDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuikShopDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuikShopDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuikShopDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuikShopDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QuikShopDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuikShopDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuikShopDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuikShopDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QuikShopDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuikShopDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuikShopDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuikShopDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuikShopDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QuikShopDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuikShopDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuikShopDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuikShopDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuikShopDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuikShopDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QuikShopDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuikShopDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QuikShopDB] SET  MULTI_USER 
GO
ALTER DATABASE [QuikShopDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuikShopDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuikShopDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QuikShopDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QuikShopDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QuikShopDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QuikShopDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [QuikShopDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QuikShopDB]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 12/15/2024 11:33:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[categoryID] [int] IDENTITY(1,1) NOT NULL,
	[categoryName] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[categoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[categoryName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CheckoutCart]    Script Date: 12/15/2024 11:33:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CheckoutCart](
	[cartID] [int] IDENTITY(1,1) NOT NULL,
	[userID] [int] NOT NULL,
	[productID] [int] NOT NULL,
	[quantity] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cartID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 12/15/2024 11:33:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[productID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](100) NOT NULL,
	[description] [nvarchar](255) NOT NULL,
	[price] [decimal](10, 2) NOT NULL,
	[images] [nvarchar](max) NOT NULL,
	[manufacturer] [nvarchar](100) NOT NULL,
	[dimensions] [nvarchar](50) NOT NULL,
	[weight] [decimal](10, 2) NOT NULL,
	[rating] [decimal](3, 2) NOT NULL,
	[SKU] [nvarchar](50) NOT NULL,
	[categoryID] [int] NOT NULL,
	[stock] [int] NOT NULL,
	[saleID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[productID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SKU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sales]    Script Date: 12/15/2024 11:33:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sales](
	[saleID] [int] IDENTITY(1,1) NOT NULL,
	[discountAmount] [decimal](5, 2) NOT NULL,
	[startDate] [date] NOT NULL,
	[endDate] [date] NOT NULL,
	[isPercentage] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[saleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 12/15/2024 11:33:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[userID] [int] IDENTITY(1,1) NOT NULL,
	[username] [nvarchar](50) NOT NULL,
	[firstName] [nvarchar](50) NOT NULL,
	[lastName] [nvarchar](50) NOT NULL,
	[address] [nvarchar](255) NULL,
	[email] [nvarchar](100) NOT NULL,
	[phoneNumber] [nvarchar](15) NULL,
	[password] [nvarchar](255) NOT NULL,
	[creditcardNumber] [nvarchar](255) NULL,
	[creditcardExpDate] [nvarchar](255) NULL,
	[cvv] [int] NULL,
	[shippingLocation] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CheckoutCart]  WITH CHECK ADD FOREIGN KEY([productID])
REFERENCES [dbo].[Products] ([productID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CheckoutCart]  WITH CHECK ADD FOREIGN KEY([userID])
REFERENCES [dbo].[users] ([userID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([categoryID])
REFERENCES [dbo].[Categories] ([categoryID])
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([saleID])
REFERENCES [dbo].[Sales] ([saleID])
GO
ALTER TABLE [dbo].[CheckoutCart]  WITH CHECK ADD CHECK  (([quantity]>=(0)))
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([rating]>=(0) AND [rating]<=(5)))
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([stock]>=(0)))
GO
USE [master]
GO
ALTER DATABASE [QuikShopDB] SET  READ_WRITE 
GO
